#include <iostream>
#include <string>
#include <cctype>
#include <fstream>

using namespace std;

class Problem
{
private:
    int problemId;
    string areaType;
    string municipality;
    string ward;

    string description;
    string category;
    string solution;
    string helper;
    string place;
    string information;
    string status;
    string priority;

public:
    void inputProblem();
    void selectInputMethod();
    void identifyCategory();
    void chooseCategory();
    void showGuidance();
    void calculatePriority();
    void getFeedback();
    void showProblem();
};

/* Enter basic problem details */
void Problem::inputProblem()
{
    int nextProblemId = 1001;

    // Read the last ID from the file
    ifstream file("last_id.txt");

    if (file)
    {
        file >> nextProblemId;
        file.close();
    }

    problemId = nextProblemId;

    // Save the next ID for the next user
    ofstream outfile("last_id.txt");

    if (outfile)
    {
        outfile << nextProblemId + 1;
        outfile.close();
    }

    cout << "\nProblem ID generated by SAHAYAK: "
         << problemId << endl;

    cout << "Enter Area Type (Rural/Urban): ";
    cin >> areaType;

    if (areaType == "Urban" || areaType == "urban")
    {
        cout << "Enter Ward Number: ";
        cin >> ward;

        // Ward to Municipality mapping
        if (ward == "1")
        {
            municipality = "Municipality A";
        }
        else if (ward == "2")
        {
            municipality = "Municipality A";
        }
        else if (ward == "3")
        {
            municipality = "Municipality B";
        }
        else if (ward == "4")
        {
            municipality = "Municipality B";
        }
        else
        {
            municipality = "Other Municipality";
        }

        cout << "Municipality: " << municipality << endl;
    }
    else
    {
        cout << "Rural area selected." << endl;
    }
}

/* Choose how the user wants to get help */
void Problem::selectInputMethod()
{
    int choice;

    cout << "\n========== HOW DO YOU WANT TO GET HELP? ==========\n";
    cout << "1. Write my problem\n";
    cout << "2. Choose a category\n";
    cout << "Enter your choice: ";
    cin >> choice;

    if (choice == 1)
    {
        cin.ignore();

        cout << "\nDescribe your problem: ";
        getline(cin, description);

        identifyCategory();
    }
    else if (choice == 2)
    {
        chooseCategory();
    }
    else
    {
        cout << "\nInvalid choice. Please try again.\n";
        category = "Other";
        status = "Unresolved";
    }
}

/* Identify category using simple keyword matching */
void Problem::identifyCategory()
{
    string text = description;

    for (char &c : text)
    {
        c = static_cast<char>(
            tolower(static_cast<unsigned char>(c))
        );
    }

    /* Property/House Tax is checked before Housing */

    if (text.find("property tax") != string::npos ||
        text.find("house tax") != string::npos ||
        text.find("ghar tax") != string::npos ||
        text.find("gharpatty") != string::npos ||
        text.find("ghar patti") != string::npos ||
        text.find("tax payment") != string::npos)
    {
        category = "Property & House Tax";
    }

    else if (text.find("water") != string::npos ||
             text.find("pani") != string::npos ||
             text.find("tap") != string::npos)
    {
        category = "Water";
    }

    else if (text.find("waste") != string::npos ||
             text.find("garbage") != string::npos ||
             text.find("dustbin") != string::npos ||
             text.find("kachra") != string::npos)
    {
        category = "Waste & Cleanliness";
    }

    else if (text.find("electricity") != string::npos ||
             text.find("electric") != string::npos ||
             text.find("light") != string::npos ||
             text.find("bijli") != string::npos)
    {
        category = "Electricity";
    }

    else if (text.find("road") != string::npos ||
             text.find("rasta") != string::npos ||
             text.find("pothole") != string::npos)
    {
        category = "Road";
    }

    else if (text.find("hospital") != string::npos ||
             text.find("doctor") != string::npos ||
             text.find("health") != string::npos ||
             text.find("medical") != string::npos)
    {
        category = "Health";
    }

    else if (text.find("school") != string::npos ||
             text.find("college") != string::npos ||
             text.find("education") != string::npos ||
             text.find("student") != string::npos)
    {
        category = "Education";
    }

    else if (text.find("aadhaar") != string::npos ||
             text.find("aadhar") != string::npos ||
             text.find("certificate") != string::npos ||
             text.find("document") != string::npos ||
             text.find("government") != string::npos)
    {
        category = "Government Services & Documents";
    }

    else if (text.find("farmer") != string::npos ||
             text.find("farming") != string::npos ||
             text.find("crop") != string::npos ||
             text.find("agriculture") != string::npos ||
             text.find("kisan") != string::npos)
    {
        category = "Agriculture";
    }

    else if (text.find("job") != string::npos ||
             text.find("employment") != string::npos ||
             text.find("work") != string::npos)
    {
        category = "Employment";
    }

    else if (text.find("bus") != string::npos ||
             text.find("transport") != string::npos ||
             text.find("vehicle") != string::npos)
    {
        category = "Transport";
    }

    else if (text.find("online") != string::npos ||
             text.find("internet") != string::npos ||
             text.find("digital") != string::npos ||
             text.find("app") != string::npos)
    {
        category = "Digital Services";
    }

    else if (text.find("pollution") != string::npos ||
             text.find("environment") != string::npos ||
             text.find("tree") != string::npos)
    {
        category = "Environment";
    }

    else if (text.find("product") != string::npos ||
             text.find("shop") != string::npos ||
             text.find("refund") != string::npos ||
             text.find("consumer") != string::npos)
    {
        category = "Consumer Problem";
    }

    else if (text.find("house") != string::npos ||
             text.find("housing") != string::npos ||
             text.find("home") != string::npos)
    {
        category = "Housing";
    }

    else
    {
        category = "Other";
    }
}

/* Manual category selection */
void Problem::chooseCategory()
{
    int choice;

    cout << "\n========== SELECT CATEGORY ==========\n";

    cout << "1. Water\n";
    cout << "2. Waste & Cleanliness\n";
    cout << "3. Electricity\n";
    cout << "4. Road\n";
    cout << "5. Health\n";
    cout << "6. Education\n";
    cout << "7. Government Services & Documents\n";
    cout << "8. Agriculture\n";
    cout << "9. Property & House Tax\n";
    cout << "10. Housing\n";
    cout << "11. Employment\n";
    cout << "12. Transport\n";
    cout << "13. Digital Services\n";
    cout << "14. Environment\n";
    cout << "15. Consumer Problem\n";
    cout << "16. Other\n";

    cout << "\nEnter your choice: ";
    cin >> choice;

    switch (choice)
    {
        case 1:
            category = "Water";
            break;

        case 2:
            category = "Waste & Cleanliness";
            break;

        case 3:
            category = "Electricity";
            break;

        case 4:
            category = "Road";
            break;

        case 5:
            category = "Health";
            break;

        case 6:
            category = "Education";
            break;

        case 7:
            category = "Government Services & Documents";
            break;

        case 8:
            category = "Agriculture";
            break;

        case 9:
            category = "Property & House Tax";
            break;

        case 10:
            category = "Housing";
            break;

        case 11:
            category = "Employment";
            break;

        case 12:
            category = "Transport";
            break;

        case 13:
            category = "Digital Services";
            break;

        case 14:
            category = "Environment";
            break;

        case 15:
            category = "Consumer Problem";
            break;

        case 16:
            category = "Other";
            break;

        default:
            category = "Other";
            cout << "Invalid choice. Category set to Other.\n";
    }

    cin.ignore();

    cout << "\nDescribe your problem: ";
    getline(cin, description);
}

/* Display guidance according to category */
void Problem::showGuidance()
{
    cout << "\n========== SAHAYAK GUIDANCE ==========\n";

    if (category == "Water")
    {
        solution = "Report the water supply problem to the concerned local authority.";
        helper = "Gram Panchayat / Municipal authority / Water supply department";
        place = "Concerned local authority office or official service channel";
        information = "Area name and details of the water problem";
    }

    else if (category == "Waste & Cleanliness")
    {
        solution = "Report the waste or cleanliness issue to the concerned local authority.";
        helper = "Gram Panchayat / Municipal authority";
        place = "Concerned local authority office or official complaint channel";
        information = "Area/location and description of the issue";
    }

    else if (category == "Electricity")
    {
        solution = "Report the electricity issue to the electricity service provider.";
        helper = "Electricity department / Local electricity service provider";
        place = "Nearest electricity office or official complaint channel";
        information = "Consumer number, location and issue details";
    }

    else if (category == "Road")
    {
        solution = "Report the damaged or unsafe road to the concerned local authority.";
        helper = "Gram Panchayat / Municipal authority / Public Works Department";
        place = "Concerned local authority office or official complaint channel";
        information = "Road location and description of the problem";
    }

    else if (category == "Health")
    {
        solution = "Visit an appropriate health facility or consult a qualified healthcare professional.";
        helper = "Government hospital / Primary Health Centre / Healthcare professional";
        place = "Nearest suitable health facility";
        information = "Basic details of the health problem";
    }

    else if (category == "Education")
    {
        solution = "Contact the concerned school, college or education authority.";
        helper = "School/college administration or education department";
        place = "Concerned educational institution or office";
        information = "Student details and description of the issue";
    }

    else if (category == "Government Services & Documents")
    {
        solution = "Contact the concerned government office or use its official service channel.";
        helper = "Concerned government department / Citizen service centre";
        place = "Relevant government office or official online service";
        information = "Required personal and document details as applicable";
    }

    else if (category == "Agriculture")
    {
        solution = "Contact the local agriculture department or an appropriate agriculture service centre.";
        helper = "Agriculture department / Agriculture service centre";
        place = "Nearest agriculture office or official service channel";
        information = "Crop details, area and description of the issue";
    }

    else if (category == "Property & House Tax")
    {
        solution = "Check the property or house tax procedure of the concerned local authority.";
        helper = "Gram Panchayat / Municipal authority";
        place = "Concerned local authority office or official online service";
        information = "Property details and applicable documents";
    }

    else if (category == "Housing")
    {
        solution = "Contact the concerned local authority or housing-related department.";
        helper = "Gram Panchayat / Municipal authority / Housing authority";
        place = "Concerned local authority office";
        information = "Address and details of the housing problem";
    }

    else if (category == "Employment")
    {
        solution = "Check suitable employment services, career centres or official job portals.";
        helper = "Employment office / Career centre / Official employment service";
        place = "Nearest employment or career service centre";
        information = "Education, skills and employment requirements";
    }

    else if (category == "Transport")
    {
        solution = "Contact the concerned transport service or local transport authority.";
        helper = "Transport department / Local transport authority";
        place = "Nearest transport office or official service channel";
        information = "Route, location and details of the transport problem";
    }

    else if (category == "Digital Services")
    {
        solution = "Check the official service/app support or visit a suitable digital service centre.";
        helper = "Official service support / Digital service centre";
        place = "Official service channel or nearby service centre";
        information = "Service name and description of the problem";
    }

    else if (category == "Environment")
    {
        solution = "Report the environmental issue to the concerned local authority.";
        helper = "Local authority / Environment-related department";
        place = "Concerned local authority office or official complaint channel";
        information = "Location and description of the environmental issue";
    }

    else if (category == "Consumer Problem")
    {
        solution = "Keep the bill or purchase details and contact the seller/service provider first.";
        helper = "Seller/service provider / Appropriate consumer support authority";
        place = "Seller/service provider or official consumer service channel";
        information = "Bill, purchase details and description of the problem";
    }

    else
    {
        cout << "\nNo suitable guidance was found for this problem.\n";
        cout << "Try describing the problem differently or choose a category manually.\n";

        status = "Unresolved";
        return;
    }

    status = "Guidance Found";

    cout << "\nCategory      : " << category << endl;
    cout << "What to do    : " << solution << endl;
    cout << "Who can help  : " << helper << endl;
    cout << "Where to go   : " << place << endl;
    cout << "Information   : " << information << endl;
    cout << "Status        : " << status << endl;

    if (areaType == "Urban" || areaType == "urban")
    {
        cout << "Ward          : " << ward << endl;
        cout << "Municipality  : " << municipality << endl;
    }

    cout << "======================================\n";
}

/* Calculate priority of the problem */
void Problem::calculatePriority()
{
    if (category == "Other")
    {
        priority = "Not Available";

        cout << "\nPriority      : " << priority << endl;
        return;
    }

    if (category == "Health" ||
        category == "Road" ||
        category == "Electricity" ||
        category == "Water")
    {
        priority = "High";
    }

    else if (category == "Waste & Cleanliness" ||
             category == "Environment" ||
             category == "Transport")
    {
        priority = "Medium";
    }

    else
    {
        priority = "Normal";
    }

    cout << "\nPriority      : " << priority << endl;
}

/* Feedback from user */
void Problem::getFeedback()
{
    int choice;

    if (status == "Unresolved")
        return;

    cout << "\n========== GUIDANCE FEEDBACK ==========\n";
    cout << "Was this guidance helpful?\n";
    cout << "1. Yes\n";
    cout << "2. No\n";
    cout << "Enter your choice: ";
    cin >> choice;

    if (choice == 1)
    {
        status = "Resolved";

        cout << "\nThank you for your feedback!\n";
        cout << "Problem status: Resolved\n";
    }

    else if (choice == 2)
    {
        status = "Unresolved";

        cout << "\nProblem status: Unresolved\n";
        cout << "You can try describing the problem differently or choose another category.\n";
    }

    else
    {
        cout << "\nInvalid feedback choice.\n";
    }
}

/* Display final problem information */
void Problem::showProblem()
{
    cout << "\n========== PROBLEM SUMMARY ==========\n";

    cout << "Problem ID  : " << problemId << endl;
    cout << "Area Type   : " << areaType << endl;

    if (areaType == "Urban" || areaType == "urban")
    {
        cout << "Ward        : " << ward << endl;
        cout << "Municipality: " << municipality << endl;
    }

    cout << "Problem     : " << description << endl;
    cout << "Category    : " << category << endl;
    cout << "Priority    : " << priority << endl;
    cout << "Status      : " << status << endl;

    cout << "=====================================\n";

    /* SAVE RECORD */

    ofstream file("sahayak_records.txt", ios::app);

    if (file)
    {
        file << "\n========== PROBLEM RECORD ==========\n";

        file << "Problem ID   : " << problemId << endl;
        file << "Area Type    : " << areaType << endl;

        if (areaType == "Urban" || areaType == "urban")
        {
            file << "Ward         : " << ward << endl;
            file << "Municipality : " << municipality << endl;
        }

        file << "Problem      : " << description << endl;
        file << "Category     : " << category << endl;
        file << "Priority     : " << priority << endl;
        file << "Status       : " << status << endl;

        file << "=====================================\n";

        file.close();

        cout << "\nRecord saved successfully!\n";
    }
    else
    {
        cout << "\nError: Record could not be saved.\n";
    }
}

/* Main function */
int main()
{
    Problem p;
    int choice;

    cout << "\n============================================\n";
    cout << "       SAHAYAK - PUBLIC PROBLEM GUIDE\n";
    cout << "============================================\n";

    do
    {
        cout << "\n============== MAIN MENU ==============\n";
        cout << "1. Get Help\n";
        cout << "2. Exit\n";
        cout << "Enter your choice: ";
        cin >> choice;

        switch (choice)
        {
            case 1:

                p.inputProblem();

                p.selectInputMethod();

                p.showGuidance();

                p.calculatePriority();

                p.getFeedback();

                p.showProblem();

                break;

            case 2:

                cout << "\nThank you for using SAHAYAK!\n";

                break;

            default:

                cout << "\nInvalid choice. Please try again.\n";
        }

    } while (choice != 2);

    return 0;
}